app_alias={
    #-6
    "shut down":"shutdown", "sure don't":"shut down", "shadow":"shutdown", "said don't":"shutdown", "shit don't":"shutdown","shutdown":"shutdown", "should do":"shutdown", "shut down":"shutdown", "should don't":"shutdown", "shit don't":"shutdown", "should the":"shutdown",
    #-5
    "lock":"lock", "look":"lock",
    #-4
    "look good":"log out", "look up":"logout","the got": "logout","log out":"logout", "look out":"logout", "lookout":"logout", "logout":"logout", "lo got":"logout", "look out":"logout", "look of":"logout", "look at":"logout",
    #-3
    "cookies him":"calculator", "cookies or":"calculator", "glitter":"calculator",
    #-2
    "up on":"open", "on":"open", "pin":"open", "hoping":"open", "helping":"open",
    #-1
    "clause":"close", "clues":"close", "those":"close", "the":"close",
    # --- 1) chrome ---
    "crop": "chrome", "crone": "chrome", "crome": "chrome", "chome": "chrome",
    "crowm": "chrome", "krome": "chrome", "chroma": "chrome", "chorome": "chrome",
    "chrone": "chrome", "chromee": "chrome", "chrime": "chrome", "chorme": "chrome",
    "crohm": "chrome", "chrom": "chrome", "chromm": "chrome", "croam": "chrome",
    "chromi": "chrome", "chroam": "chrome", "crhom": "chrome", "chrohm": "chrome",
    "crhome": "chrome", "khrone": "chrome", "qrome": "chrome", "croom": "chrome",
    "chrmoe": "chrome", "chromw": "chrome", "chromu": "chrome", "chromr": "chrome",
    "chrume": "chrome", "chrowm": "chrome", "chrome browser": "chrome",
    "google chrome": "chrome", "google crom": "chrome", "google crome": "chrome",
    "google crone": "chrome", "gogle chrome": "chrome", "googl chrome": "chrome", "crew":"chrome", "crops":"chrome", "crow":"chrome", "curb":"chrome",
    "crumb":"chrome", "crow":"chrome", "from":"chrome", "cropped":"chrome",
    # --- 2) firefox ---
    "fire fox": "firefox", "firfox": "firefox", "fierfox": "firefox", "fyrefox": "firefox",
    "firevox": "firefox", "firefax": "firefox", "firefoxx": "firefox", "fire focks": "firefox",
    "firefoz": "firefox", "firephox": "firefox", "firefok": "firefox", "firofox": "firefox",
    "firefex": "firefox", "firfoks": "firefox", "firefoos": "firefox", "fire phox": "firefox",
    "fyrefoks": "firefox", "fire fawks": "firefox", "firefog": "firefox", "firefloks": "firefox",
    "fierfocks": "firefox", "firefocs": "firefox", "firefox browser": "firefox", "federal":"firefox", "federals":"firefox",
    "mozilla": "firefox", "mozila": "firefox", "mozella": "firefox", "mozla": "firefox", "folk":"firefox", "folks":"firefox",
    "mozela": "firefox", "mozillax": "firefox", "mozill": "firefox", "mozzilla": "firefox", "for folks": "firefox",
    "mozila firefox": "firefox", "mozillaa": "firefox", "mozillia": "firefox", "for folks":"firefox", "fed fox":"firefox", "fairfox":"firefox", "fairfax":"firefox", 

    # --- 3) vscode --- FIXED: Now maps to "code" instead of "vscode"
    "vscode": "code", "could":"code", "vs code": "code", "face code":"code", "v s code": "code", "visco": "code", "bscode": "code",
    "viscoed": "code", "visko": "code", "vescode": "code", "vizcode": "code",
    "vs coed": "code", "vs cod": "code", "vscodee": "code", "viscode": "code",
    "vscode app": "code", "visual studio code": "code", "visual studio": "code",
    "visualcode": "code", "visual code": "code", "vis studio": "code",
    "vstudio code": "code", "vscod": "code", "vsco":"code", "vscude": "code",
    "vsxode": "code", "vescod": "code", "vsc0de": "code", "vscold": "code",
    "viscod": "code", "vs coder": "code", "vs codr": "code", "code": "code",
    "code editor": "code", "codee": "code", "codes": "code", "cod": "code", "faced could":"code",
    "facecloud":"code", "faced good":"code", "first good":"code", "fist could":"code", "viz good":"code", "this could":"code",

    # --- 4) slack ---
    "slak": "slack", "slag": "slack", "slck": "slack", "slcak": "slack", "slac": "slack",
    "slackk": "slack", "slack app": "slack", "slack chat": "slack",
    "slack messenger": "slack", "slack desktop": "slack", "sluck": "slack",
    "slackc": "slack", "stack": "slack", "slacke": "slack", "slacks": "slack",
    "slax": "slack", "slakk": "slack", "slacc": "slack", "slqck": "slack",
    "slack dot": "slack", "slack dot com": "slack", "select": "slack",
    "slacko": "slack", "slac app": "slack", "slac chat": "slack", "slaka": "slack",
    "slack workspace": "slack", "slack client": "slack", "slackk app": "slack", "slag":"slack",
    "slack application": "slack", "slot":"slack", "slug":"slack", "look":"slack", "stuck":"slack",

    # --- 5) discord ---
    "this cord": "discord", "diskord": "discord", "dischord": "discord", "discrod": "discord",
    "disocrd": "discord", "discord app": "discord", "discordd": "discord", "discorde": "discord",
    "dicsord": "discord", "disord": "discord", "discod": "discord", "dis court": "discord",
    "dis core": "discord", "discor": "discord", "dizcord": "discord", "discord chat": "discord",
    "discord messenger": "discord", "discord desktop": "discord", "discords": "discord",
    "discordapp": "discord", "discord dot com": "discord", "discrod app": "discord",
    "dis code": "discord", "disk or d": "discord", "discard": "discord",
    "dischord app": "discord", "the discord": "discord", "discorde app": "discord",
    "discourd": "discord", "discort": "discord",

    # --- 6) zoom ---
    "zooom": "zoom", "zoom app": "zoom", "doom": "zoom", "zoon": "zoom",
    "zoome": "zoom", "zom": "zoom", "zum": "zoom", "zoomm": "zoom",
    "zoom meeting": "zoom", "zoom video": "zoom", "zoomb": "zoom", "zoonm": "zoom",
    "zoem": "zoom", "zoomms": "zoom", "z0om": "zoom", "zoomee": "zoom",
    "zume": "zoom", "zoon app": "zoom", "zoom desktop": "zoom",
    "zoomeet": "zoom", "zoomit": "zoom", "zoomr": "zoom", "zoomz": "zoom",
    "zoomx": "zoom", "zoom chat": "zoom", "zoom call": "zoom",
    "zoom cloud": "zoom", "zoom video call": "zoom", "zoom software": "zoom",
    "zoom tool": "zoom", "zoomroom": "zoom",

    # --- 7) telegram-desktop ---
    "tele gram": "telegram-desktop", "telegram": "telegram-desktop",
    "telegrame": "telegram-desktop", "telegramm": "telegram-desktop",
    "telagram": "telegram-desktop", "telegarm": "telegram-desktop",
    "telegra": "telegram-desktop", "telegrap": "telegram-desktop",
    "telegram app": "telegram-desktop", "telegram desktop": "telegram-desktop",
    "telegr": "telegram-desktop", "telgrm": "telegram-desktop",
    "tellegram": "telegram-desktop", "telegramme": "telegram-desktop",
    "teligram": "telegram-desktop", "telegran": "telegram-desktop",
    "telegram chat": "telegram-desktop", "telegram messenger": "telegram-desktop",
    "telegrapm": "telegram-desktop", "telegramdot": "telegram-desktop",
    "telegrqm": "telegram-desktop", "telegrum": "telegram-desktop",
    "teligarm": "telegram-desktop", "telegrem": "telegram-desktop",
    "telegr4m": "telegram-desktop", "tele gram app": "telegram-desktop",
    "telegram tool": "telegram-desktop", "telegram service": "telegram-desktop",
    "telegram desk": "telegram-desktop", "telegr desktop": "telegram-desktop",

    # --- 8) spotify ---
    "spot if i": "spotify", "sportify": "spotify", "spotty fi": "spotify",
    "spoitfy": "spotify", "spootify": "spotify", "sotify": "spotify",
    "spottify": "spotify", "soptify": "spotify", "spofty": "spotify",
    "spodify": "spotify", "spoofy": "spotify", "spotfy": "spotify",
    "spotifi": "spotify", "spoti": "spotify", "spoify": "spotify",
    "spotfy app": "spotify", "spotify app": "spotify", "spotify desktop": "spotify",
    "spotify music": "spotify", "spotifyy": "spotify", "spotiffy": "spotify",
    "spotfy music": "spotify", "spoti music": "spotify", "spotfy tool": "spotify",
    "spofity": "spotify", "sp0tify": "spotify", "spotaphy": "spotify",
    "spota fy": "spotify", "spottfi": "spotify", "spotyfi": "spotify",
    "spot phie": "spotify", "spoti app": "spotify",

    # --- 9) vlc ---
    "v l c": "vlc", "vlc player": "vlc", "valsea": "vlc", "vlce": "vlc",
    "vl see": "vlc", "vlic": "vlc", "vlcc": "vlc", "vlci": "vlc",
    "vlck": "vlc", "vlc media": "vlc", "vlc media player": "vlc",
    "vlcs": "vlc", "vls": "vlc", "vlsc": "vlc", "vlcz": "vlc",
    "vlcq": "vlc", "vlcm": "vlc", "vlch": "vlc", "vlct": "vlc",
    "vlcp": "vlc", "vlcx": "vlc", "vlcv": "vlc", "vlcb": "vlc",
    "vlcn": "vlc", "vlcd": "vlc", "vlcf": "vlc", "vlcj": "vlc",
    "vlck player": "vlc", "vlci player": "vlc", "vlc desktop": "vlc",
    "vlcapp": "vlc", "vlc dot": "vlc",

    # --- 10) gimp ---
    "gimp app": "gimp", "gimpf": "gimp", "gymp": "gimp", "chimp": "gimp",
    "gimpp": "gimp", "jimp": "gimp", "gim": "gimp", "gimp editor": "gimp",
    "gimp image": "gimp", "gimp tool": "gimp", "gimp program": "gimp",
    "gimp desktop": "gimp", "gimp software": "gimp", "gimpe": "gimp",
    "gimppp": "gimp", "gimpt": "gimp", "gimped": "gimp", "gimpi": "gimp",
    "gimpo": "gimp", "gimping": "gimp", "gimpic": "gimp", "gimpc": "gimp",
    "gimpz": "gimp", "gimpy": "gimp", "gimp photo": "gimp", "gimp art": "gimp",
    "gimp draw": "gimp", "gimp paint": "gimp", "gimp dot": "gimp",
    "gimp photo editor": "gimp",

    # --- 11) inkscape ---
    "ink scape": "inkscape", "inskape": "inkscape", "in scape": "inkscape",
    "inkscape app": "inkscape", "ink scae": "inkscape", "inkscpae": "inkscape",
    "inkscp": "inkscape", "ink scap": "inkscape", "ink shape": "inkscape",
    "inkscape tool": "inkscape", "inkscape editor": "inkscape",
    "inkscap": "inkscape", "inkscapee": "inkscape", "ink scaper": "inkscape",
    "inkscape draw": "inkscape", "ink scape program": "inkscape",
    "inkscape desktop": "inkscape", "ink scape paint": "inkscape",
    "inkscape paint": "inkscape", "ink escape": "inkscape", "inkscsape": "inkscape",
    "inkscae": "inkscape", "inscape": "inkscape", "inxcape": "inkscape",
    "inskcape": "inkscape", "ink scpe": "inkscape", "ink scapey": "inkscape",
    "inkscape art": "inkscape", "inkscape draw app": "inkscape",
    "ink scape editor": "inkscape", "inkscape vector": "inkscape",

    # --- 12) krita ---
    "creta": "krita", "kritter": "krita", "kreeta": "krita", "kreetah": "krita",
    "kritaa": "krita", "kritar": "krita", "kryta": "krita", "crita": "krita",
    "krrita": "krita", "krits": "krita", "kritta": "krita", "krirta": "krita",
    "krtia": "krita", "kreetta": "krita", "krita app": "krita",
    "krita desktop": "krita", "krita tool": "krita", "krita paint": "krita",
    "krita art": "krita", "krita drawing": "krita", "krita painter": "krita",
    "krita paint app": "krita", "krita software": "krita", "krita program": "krita",
    "krita design": "krita", "krita editor": "krita", "krita art app": "krita",
    "krita paint tool": "krita", "krita draw": "krita",

    # --- 13) obs-studio ---
    "obs": "obs-studio", "o b s": "obs-studio", "obvious studio": "obs-studio",
    "obsstudio": "obs-studio", "obs studio": "obs-studio", "obs tool": "obs-studio",
    "ob studio": "obs-studio", "ob s": "obs-studio", "obs st": "obs-studio",
    "obes": "obs-studio", "obb studio": "obs-studio", "obss": "obs-studio",
    "obs streaming": "obs-studio", "obs record": "obs-studio",
    "obs video": "obs-studio", "obs program": "obs-studio",
    "obs stream": "obs-studio", "obs application": "obs-studio",
    "obs desktop": "obs-studio", "obs rec": "obs-studio",
    "obs stream app": "obs-studio", "obs studio app": "obs-studio",
    "obs stud": "obs-studio", "obs record tool": "obs-studio",
    "obs cast": "obs-studio", "obs broadcast": "obs-studio",
    "obs live": "obs-studio", "obs live stream": "obs-studio",
    "obs tv": "obs-studio",

    # --- 14) audacity ---
    "audacity app": "audacity", "odyssey": "audacity", "audisity": "audacity",
    "audacityy": "audacity", "audacit": "audacity", "audaciti": "audacity",
    "audicty": "audacity", "audacitiy": "audacity", "audatcity": "audacity",
    "audicy": "audacity", "audacidy": "audacity", "audacity software": "audacity",
    "audacity program": "audacity", "audacity tool": "audacity",
    "audacity sound": "audacity", "audacity audio": "audacity",
    "audacity record": "audacity", "audacity editor": "audacity",
    "audacity desktop": "audacity", "audacity music": "audacity",
    "audacity studio": "audacity", "audacit app": "audacity",
    "audacity application": "audacity", "audacity recorder": "audacity",
    "audacity voice": "audacity", "audacity rec": "audacity",
    "audaciti app": "audacity", "audiciti": "audacity",

    # --- 15) steam ---
    "steem": "steam", "esteem": "steam", "stim": "steam", "steam app": "steam",
    "steam desktop": "steam", "steam tool": "steam", "steamm": "steam",
    "steme": "steam", "stam": "steam", "stam app": "steam", "steme app": "steam",
    "stiam": "steam", "stiem": "steam", "stean": "steam", "steaam": "steam",
    "st3am": "steam", "stheam": "steam", "steeam": "steam", "steami": "steam",
    "steam store": "steam", "steam game": "steam", "steam client": "steam",
    "steam games": "steam", "steamsoft": "steam", "steam application": "steam",
    "steam software": "steam", "steam gaming": "steam", "steam platform": "steam",
    "steam account": "steam", "steam dot": "steam",

    # --- 16) thunderbird ---
    "thunder bird": "thunderbird", "thunderbud": "thunderbird",
    "thunderbert": "thunderbird", "thunderbord": "thunderbird",
    "thunderburd": "thunderbird", "thundrbird": "thunderbird",
    "thundrbud": "thunderbird", "thunderbrid": "thunderbird",
    "thunderberd": "thunderbird", "thundarbird": "thunderbird",
    "thunder berd": "thunderbird", "thunder bird app": "thunderbird",
    "thunderbird app": "thunderbird", "thunderbird email": "thunderbird",
    "thunderbird mail": "thunderbird", "thunderbird client": "thunderbird",
    "thunderbird desktop": "thunderbird", "thunderbird software": "thunderbird",
    "thunderbird program": "thunderbird", "thunderbird email app": "thunderbird",
    "thunder bird mail": "thunderbird", "thunder bird program": "thunderbird",
    "thunder brd": "thunderbird", "thunderbd": "thunderbird",
    "thundebird": "thunderbird", "thundebud": "thunderbird",
    "thunderbord app": "thunderbird", "thundrbird mail": "thunderbird",
    "moz thunderbird": "thunderbird",

    # --- 17) libreoffice-writer ---
    "libre writer": "libreoffice-writer", "writer": "libreoffice-writer",
    "liber writer": "libreoffice-writer", "library writer": "libreoffice-writer",
    "libre wri": "libreoffice-writer", "libre office write": "libreoffice-writer",
    "libre write": "libreoffice-writer", "librewriter": "libreoffice-writer",
    "libreoff writer": "libreoffice-writer", "librewritr": "libreoffice-writer",
    "libre write app": "libreoffice-writer", "librewrit": "libreoffice-writer",
    "libreoffice write": "libreoffice-writer", "libre office writer": "libreoffice-writer",
    "libra writer": "libreoffice-writer", "librewritre": "libreoffice-writer",
    "libreoffic writer": "libreoffice-writer", "libreoffice write app": "libreoffice-writer",
    "libreoffice writr": "libreoffice-writer", "libreoffice writer app": "libreoffice-writer",
    "libre writer program": "libreoffice-writer", "librewriterr": "libreoffice-writer",
    "libre office writer app": "libreoffice-writer", "libreoffice write tool": "libreoffice-writer",
    "librewritting": "libreoffice-writer", "libreoff write": "libreoffice-writer",
    "libreoffic write": "libreoffice-writer", "librewriterrr": "libreoffice-writer",

    # --- 18) libreoffice-calc ---
    "libre calc": "libreoffice-calc", "calc": "libreoffice-calc",
    "liber calc": "libreoffice-calc", "libre clac": "libreoffice-calc",
    "libre cal": "libreoffice-calc", "libre office calc": "libreoffice-calc",
    "libreoff calc": "libreoffice-calc", "libre calk": "libreoffice-calc",
    "librecalc": "libreoffice-calc", "libre calcu": "libreoffice-calc",
    "libre calcc": "libreoffice-calc", "libra calc": "libreoffice-calc",
    "libreoffice calc app": "libreoffice-calc", "libreoffice calcul": "libreoffice-calc",
    "libre calcs": "libreoffice-calc", "libre office calk": "libreoffice-calc",
    "libreoffic calc": "libreoffice-calc", "libre off calc": "libreoffice-calc",
    "libre offce calc": "libreoffice-calc", "libreoffice cal": "libreoffice-calc",
    "libreoffice calq": "libreoffice-calc", "libreoffice calcs": "libreoffice-calc",
    "libre cal tool": "libreoffice-calc", "libre cal program": "libreoffice-calc",
    "libreoffice cal tool": "libreoffice-calc", "libre calc app": "libreoffice-calc",
    "calc libre": "libreoffice-calc", "calc libre office": "libreoffice-calc",

    # --- 19) libreoffice-impress ---
    "libre impress": "libreoffice-impress", "impress": "libreoffice-impress",
    "libre office impress": "libreoffice-impress", "libreoff impress": "libreoffice-impress",
    "libreoffice imp": "libreoffice-impress", "libreoffice impre": "libreoffice-impress",
    "libre imp": "libreoffice-impress", "libre office imp": "libreoffice-impress",
    "libre impress app": "libreoffice-impress", "libre office impr": "libreoffice-impress",
    "libreoffice impress app": "libreoffice-impress", "libreoffice imprss": "libreoffice-impress",
    "libreoffice impr": "libreoffice-impress", "libreoffice impress tool": "libreoffice-impress",
    "libreoffice presentation": "libreoffice-impress", "libreoffice slides": "libreoffice-impress",
    "impress libre": "libreoffice-impress", "impress libre office": "libreoffice-impress",
    "libre office slides": "libreoffice-impress", "libre office presentation": "libreoffice-impress",
    "libre pres": "libreoffice-impress", "libreoffice pres": "libreoffice-impress",
    "libreoffice present": "libreoffice-impress", "libreoffice presentations": "libreoffice-impress",
    "libre present": "libreoffice-impress", "libreoffice presnt": "libreoffice-impress",

    # --- 20) docker ---
    "dock er": "docker", "doctor": "docker", "daucker": "docker", "daukar": "docker",
    "dockr": "docker", "docer": "docker", "docker app": "docker", "docker program": "docker",
    "docker desktop": "docker", "docker software": "docker", "docker tool": "docker",
    "docker program app": "docker", "docker platform": "docker", "docker application": "docker",
    "dokker": "docker", "doccer": "docker", "docher": "docker", "dockor": "docker",
    "dokar": "docker", "dokor": "docker", "docker system": "docker", "docker cli": "docker",
    "docker compose": "docker", "docker hub": "docker", "docker hub app": "docker",
    "docker desktop app": "docker", "dockerr": "docker", "doccer app": "docker",
    "docker runtime": "docker", "docker soft": "docker",    

    # --- 21) postman ---
    "post man": "postman", "postmen": "postman", "post man app": "postman",
    "postmen app": "postman", "post man tool": "postman", "postmen tool": "postman",
    "post man program": "postman", "post man desktop": "postman",
    "postman desktop": "postman", "postman app": "postman", "postmen desktop": "postman",
    "postman software": "postman", "postman client": "postman",
    "postman api": "postman", "postmen api": "postman", "post man api": "postman",
    "postman test": "postman", "postman testing": "postman", "postman runner": "postman",
    "postman rest": "postman", "post man rest": "postman", "postmen rest": "postman",
    "postman api tool": "postman", "post man api tool": "postman",
    "postman application": "postman", "postmen application": "postman",
    "post man application": "postman", "postman tool": "postman",
    "postman run": "postman", "postman service": "postman",

    # --- 22) filezilla ---
    "file zilla": "filezilla", "files illa": "filezilla", "phil zilla": "filezilla",
    "filezila": "filezilla", "filezilla app": "filezilla", "filezilla desktop": "filezilla",
    "filezilla tool": "filezilla", "filezilla program": "filezilla",
    "filezilla client": "filezilla", "filezilla ftp": "filezilla",
    "file zila": "filezilla", "filzilla": "filezilla", "filezillas": "filezilla",
    "filezillaa": "filezilla", "filezill": "filezilla", "filezilo": "filezilla",
    "filezilla software": "filezilla", "filezilla ftp client": "filezilla",
    "filezilla ftp tool": "filezilla", "filezilla transfer": "filezilla",
    "filezilla ftp app": "filezilla", "filezillla": "filezilla",
    "filezillaaa": "filezilla", "filezillax": "filezilla", "filezilla dot": "filezilla",
    "filezilla system": "filezilla", "fileziller": "filezilla", "fileziller app": "filezilla",

    # --- 23) brave ---
    "braid": "brave", "brav": "brave", "grave": "brave", "braiv": "brave",
    "bravie": "brave", "braev": "brave", "braif": "brave", "brrave": "brave",
    "brab": "brave", "braav": "brave", "bravie browser": "brave",
    "bravee": "brave", "brav3": "brave", "b r a v e": "brave",
    "brav app": "brave", "brave browser": "brave", "brv": "brave",
    "bruv": "brave", "brufe": "brave", "brayv": "brave", "braye": "brave",
    "brabv": "brave", "brabef": "brave", "brahv": "brave", "brae browser": "brave",
    "bruve": "brave", "br4ve": "brave", "brauv": "brave", "braavv": "brave",

    # --- 24) opera ---
    "oprah": "opera", "opra": "opera", "oppera": "opera", "operaa": "opera",
    "opra browser": "opera", "oprea": "opera", "oppara": "opera", "opar": "opera",
    "o para": "opera", "opera browser": "opera", "oparrah": "opera",
    "operrra": "opera", "operr": "opera", "opra app": "opera", "oppra": "opera",
    "opraah": "opera", "opaira": "opera", "opuraa": "opera", "opirra": "opera",
    "opira": "opera", "opira browser": "opera", "opperaa": "opera",
    "oppaira": "opera", "oparrah app": "opera", "opara": "opera", "opira app": "opera",
    "opero": "opera", "opira tool": "opera", "opira software": "opera",

    # --- 25) edge ---
    "ms edge": "edge", "edje": "edge", "hedge": "edge", "edgee": "edge",
    "ej": "edge", "microsoft edge": "edge", "microsoft ej": "edge",
    "egde": "edge", "ejd": "edge", "edge browser": "edge", "edg": "edge",
    "edgj": "edge", "eedge": "edge", "ejge": "edge", "ejdge": "edge",
    "eged": "edge", "edger": "edge", "egge": "edge", "ejdge browser": "edge",
    "edj": "edge", "hedj": "edge", "hedge browser": "edge", "ms ej": "edge",
    "ejdge app": "edge", "edge app": "edge", "edge application": "edge",
    "edge tool": "edge", "edgee browser": "edge",
    # --- 26) sublime-text ---
    "sublime": "sublime-text", "sublimetext": "sublime-text",
    "sublimetex": "sublime-text", "sub lime": "sublime-text",
    "sublimee": "sublime-text", "sublim": "sublime-text",
    "sublime app": "sublime-text", "sublimed": "sublime-text",
    "sublom": "sublime-text", "sublmi": "sublime-text",
    "sublimex": "sublime-text", "subblime": "sublime-text",
    "sublime editor": "sublime-text", "sublimer": "sublime-text",
    "sublime code": "sublime-text", "sublimit": "sublime-text",
    "sublime x": "sublime-text", "sublimexx": "sublime-text",
    "sublimext": "sublime-text", "sublimet": "sublime-text",
    "sublime writing": "sublime-text", "sublimer text": "sublime-text",
    "sublime t": "sublime-text", "sublimex editor": "sublime-text",
    "sublimetx": "sublime-text", "sublimetext app": "sublime-text",
    "sublimetext editor": "sublime-text", "sublimetool": "sublime-text",

    # --- 27) gedit ---
    "g edit": "gedit", "g-editor": "gedit", "geditor": "gedit",
    "gedit app": "gedit", "gedit text": "gedit", "gedit text editor": "gedit",
    "gedit editor": "gedit", "gedits": "gedit", "geditx": "gedit",
    "geditt": "gedit", "gediit": "gedit", "gedi": "gedit", "ged it": "gedit",
    "g edit tool": "gedit", "g edit program": "gedit", "gedit desktop": "gedit",
    "gedit software": "gedit", "gedit pro": "gedit", "gedit client": "gedit",
    "gedit code": "gedit", "gedit write": "gedit", "gedit write tool": "gedit",
    "gedit writing": "gedit", "gedit writing tool": "gedit", "geditx app": "gedit",
    "geditx editor": "gedit", "gedit dot": "gedit", "gedit dot com": "gedit",

    # --- 28) kate ---
    "kate editor": "kate", "k eight": "kate", "cate": "kate",
    "kaet": "kate", "kait": "kate", "kayt": "kate", "kayte": "kate",
    "katee": "kate", "katte": "kate", "katt": "kate", "kaate": "kate",
    "kat": "kate", "ket": "kate", "kaat": "kate", "kaite": "kate",
    "kaitt": "kate", "kete": "kate", "kete editor": "kate",
    "katex": "kate", "katex editor": "kate", "kate write": "kate",
    "kate write tool": "kate", "kate program": "kate", "kate text": "kate",
    "kate text editor": "kate", "kate writing": "kate", "kate software": "kate",
    "kate pro": "kate", "kate app": "kate",

    # --- 29) neovim ---
    "neo vim": "neovim", "neovim editor": "neovim", "neo vhim": "neovim",
    "new vim": "neovim", "nevim": "neovim", "nevim app": "neovim",
    "neovim app": "neovim", "neovim tool": "neovim", "neovim software": "neovim",
    "neovim program": "neovim", "neovim desktop": "neovim", "neovim editor app": "neovim",
    "nevim editor": "neovim", "nevim tool": "neovim", "nevim desktop": "neovim",
    "nevim software": "neovim", "nevim program": "neovim",
    "neovimm": "neovim", "neovims": "neovim", "neovimx": "neovim",
    "neovime": "neovim", "neovimn": "neovim", "neovimm editor": "neovim",
    "neovime editor": "neovim", "neovimm app": "neovim", "neovime app": "neovim",
    "neovimm tool": "neovim", "neovime tool": "neovim", "neovimm program": "neovim",

    # --- 30) chromium ---
    "chromeium": "chromium", "cranium": "chromium", "chromiun": "chromium",
    "chrom iam": "chromium", "chrome um": "chromium", "chromiom": "chromium",
    "crhomium": "chromium", "kromium": "chromium", "chromum": "chromium",
    "chroomium": "chromium", "chromiunm": "chromium", "chroim": "chromium",
    "chromyon": "chromium", "chromiunx": "chromium", "chromiul": "chromium",
    "chrommum": "chromium", "chromioum": "chromium", "chromiou": "chromium",
    "chrmium": "chromium", "chromivm": "chromium", "chromiunv": "chromium",
    "chromiomn": "chromium", "chromiuum": "chromium", "chromium browser": "chromium",
    "google chromium": "chromium", "crumium": "chromium", "chromuim": "chromium",
    "chromiun app": "chromium", "chromium app": "chromium"
}






